excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://algustionesa.github.io
title: Algustionesa Yoshi
tagline: Kalamuna Lafdzun Mufidzun
description: Kalamuna Lafdzun Mufidzun
paginate: 5